### ISSUE TITLE
refactor: rename `parsed` type to `Pep440Version`

### ISSUE THREAD

**Issue by viceice** [renovatebot/pep440#117]
Rename `parsed` type to `Pep440Version`.

_Originally posted by @viceice in https://github.com/renovatebot/pep440/pull/115#r781028115_

**Comment by RahulGautamSingh** [comment]
This package needs to published again right?

**Comment by viceice** [comment]
yes, we should do a major bump to be save. But we should make all required changes before. You can use yarn link feature to test locally at renovate.

**Comment by RahulGautamSingh** [comment]
> yes, we should do a major bump to be save. But we should make all required changes before. You can use yarn link feature to test locally at renovate.

Tried yarn link it works fine on other local projects as I am able to link pep440 to them. But in the renovate dev:container yarn is unable find the local pep440.

So I tested by manually copying the files to `node_modules/@renovate/pep440` and running `yarn test/lint/null-check`

**Comment by viceice** [comment]
> Tried yarn link it works fine on other local projects as I am able to link pep440 to them. But in the renovate dev:container yarn is unable find the local pep440.
> 
> So I tested by manually copying the files to `node_modules/@renovate/pep440` and running `yarn test/lint/null-check`

You need to checkout pep440 in dev container too and link there 😉
