### ISSUE TITLE
Setup Prettier linter

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/pep440#129]
**What would you like to be able to do?**

Right now we need to manually format the code. This is a bad idea.

**Did you already have any implementation ideas?**

- [x] Install Prettier as development dependency
- [ ] Include a `prettier-fix` command in the `scripts` in `package.json`
- [x] Run a prettier lint command in the CI on pushes to `main` and incoming Pull Request

You can probably copy/paste/adjust the relevant Prettier scripts and CI setup from the main Renovate repository.

**Comment by RahulGautamSingh** [comment]
Hey @HonkingGoose can you assign me to this task, I would really like to implement this one.
