### ISSUE TITLE
incorrect type of function parameters

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/pep440#142]
In the file `lib/specifier.d.ts`
The functions `maxSatisfyingVesrion` and  `minSatisfyingVersion`, the parameter `version` have type `string` which needs to be of type  `string[]` and renamed to `versions`.

**Comment by RahulGautamSingh** [comment]
> There is another issue. The `options` parameter isn't `Pep440Version` type.

It is used as an object with the property `prereleases` in it. And then it is merged in an object which is of type `pep440Version`. Unable to figure out a specific type with this much information.😟 Any suggestions?

**Comment by viceice** [comment]
I think it should be a simple `Options` interface with only `prereleases?:boolean`

https://github.com/renovatebot/pep440/blob/160be84f01d89fd50f0721b333a4769d255452fe/lib/specifier.js#L111

https://github.com/renovatebot/pep440/blob/160be84f01d89fd50f0721b333a4769d255452fe/lib/specifier.js#L134-L140

It's used in local function `contains` but never get's outside of `pick` function

```ts
export interface Pep440SpecifierOptions {
  prereleases?: boolean;
}
```

**Comment by viceice** [comment]
Tested here:
https://github.com/renovatebot/pep440/blob/160be84f01d89fd50f0721b333a4769d255452fe/test/specifier.test.js#L492
