### ISSUE TITLE
ideas/questions for this repo

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/pep440#82]
## Migrate to GitHub Actions?

I noticed this repo has a `travis.yml` file, that's outdated (it uses Node 8).
Should we maybe migrate this to a GitHub Actions workflow and update the Node version?

## Explain what this repo is about in readme?

This repository also doesn't explain in the README what the goal of this repo is, so anybody reaching this repo can't see if they need this or not.

## Add badges for migrated GitHub Action?

Also it would be nice to have a badge for the tests on the README page, so that you can see at a glance if tests are passing/failing.

**Comment by rarkins** [comment]
Yes, we should migrate to GitHub Actions, and a README + badge would be nice.

We should also bump it to 1.0.0 once we're done.

**Comment by HonkingGoose** [comment]
Seems it's already at `1.0.0`: https://github.com/renovatebot/pep440/blob/742e504897de2b2fa775299cb00fd593b883d2dd/package.json#L2-L4

**Comment by HonkingGoose** [comment]
I'll let you guys do the migration from Travis CI to GitHub Actions. 😉
